import { S, round } from '../state.js';
import { easeString } from '../timeline.js';
import { selFor, clipSelector, exportVars, srcVars } from './shared.js';

export function genGSAP() {
  const usesDraw = S.clips.some(c => c.props.drawStart?.on || c.props.drawEnd?.on || c.props.dashGap?.on);
  const usesMP = S.clips.some(c => c.motionPath);
  const tg = S.trigger;
  const plugins = ['ScrollTrigger'].concat(usesMP ? ['MotionPathPlugin'] : []);
  let out = '';
  out += `/* Generated by SVG Animation Factory */\n`;
  out += `gsap.registerPlugin(${plugins.join(', ')});\n\n`;
  out += `const root = document.querySelector('#saf-root');\nif (root) {\n`;
  out += `  const q = sel => root.querySelectorAll(sel);\n`;
  if (usesDraw) {
    out += `  const dash = (s, e, g) => (i, el) => {\n`;
    out += `    const L = el.getTotalLength();\n`;
    out += `    return \`\${Math.max(0, e - s) * L}px \${g > 0 ? g : L + 1}px\`;\n  };\n`;
    out += `  const off = s => (i, el) => \`\${-s * el.getTotalLength()}px\`;\n`;
  }
  out += `\n  gsap.matchMedia().add('(prefers-reduced-motion: no-preference)', () => {\n`;

  const tlOpts = [`defaults: { ease: 'power2.out' }`];
  if (S.loop && tg.mode === 'load') tlOpts.push('repeat: -1');
  if (tg.mode === 'click' || tg.mode === 'hover') tlOpts.push('paused: true');
  if (tg.mode === 'scroll') tlOpts.push(`scrollTrigger: { trigger: root, start: '${tg.start}', once: ${tg.once}${tg.markers ? ', markers: true' : ''} }`);
  if (tg.mode === 'scrub') tlOpts.push(`scrollTrigger: { trigger: root, start: '${tg.start}', end: '${tg.end}', scrub: 1${tg.markers ? ', markers: true' : ''} }`);
  out += `    const tl = gsap.timeline({ ${tlOpts.join(', ')} });\n\n`;

  S.clips.filter(c => c.enabled && c.targets.length).forEach(c => {
    const sel = clipSelector(c); if (!sel) return;
    const t = c.timing;
    const toV = exportVars(c, 'to');
    const timing = { duration: t.duration, ease: easeString(t) };
    if (t.delay) timing.delay = t.delay;
    if (t.repeat) timing.repeat = t.repeat;
    if (t.yoyo) timing.yoyo = true;
    if (t.repeatDelay) timing.repeatDelay = t.repeatDelay;
    if (c.targets.length > 1 && c.stagger.amount > 0) {
      timing.stagger = `__RAW__{ amount: ${c.stagger.amount}, from: '${c.stagger.from}'` +
        (c.stagger.axis ? `, axis: '${c.stagger.axis}'` : '') +
        (c.stagger.ease !== 'none' ? `, ease: '${c.stagger.ease}'` : '') + ' }';
    }
    if (c.motionPath) {
      const g = S.byUid.get(c.motionPath);
      if (g) timing.motionPath = `__RAW__{ path: root.querySelector('${selFor(g.node.getAttribute('id'))}')` +
        (c.mpAlign ? `, align: root.querySelector('${selFor(g.node.getAttribute('id'))}'), alignOrigin: [0.5, 0.5]` : '') +
        (c.mpRotate ? ', autoRotate: true' : '') + ' }';
    }
    const merged = Object.assign({}, toV, timing);
    const fromV = exportVars(c, 'from');
    out += `    // ${c.name}  —  ${c.targets.length} target${c.targets.length > 1 ? 's' : ''}\n`;
    if (Object.keys(fromV).length)
      out += `    tl.fromTo(q('${sel}'),\n      ${srcVars(fromV)},\n      ${srcVars(merged)}, ${round(c._start || 0, 3)});\n\n`;
    else
      out += `    tl.to(q('${sel}'), ${srcVars(merged)}, ${round(c._start || 0, 3)});\n\n`;
  });

  if (tg.mode === 'click')
    out += `    root.addEventListener('click', () => tl.restart());\n    root.style.cursor = 'pointer';\n`;
  if (tg.mode === 'hover') {
    out += `    root.addEventListener('mouseenter', () => tl.play());\n`;
    out += `    root.addEventListener('mouseleave', () => tl.reverse());\n`;
  }
  out += `    return () => tl.kill();\n  });\n}\n`;
  return out;
}
